ccet_bullet/urls.py
from django.contrib import admin
from django.urls import path,include
from messenger_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('messenger_app/',include("messenger_app.urls")),
]

messenger_app/urls.py
from django.urls import path
from . import views
#setting the namespace
app_name = "messenger_app"
urlpatterns = [
path("",views.index,name="index"),
path("student_register/",views.student_register,name="student_register"),
path("login/",views.user_login,name="user_login"),
path("create_post/",views.create_post,name="create_post"),
path("about/",views.about,name="about")
# path("success/",views.reg_success,name="reg_success"),
]

messenger_app/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import date
# Create your models here.

class student(models.Model):
    stream_choices = (
    ('CSE','CSE'),
    ('ECE','ECE'),
    ('Mechanical','Mechanical'),
    ('Civil','Civil'),
    )

    year_choices = (
    (1,"1st year"),
    (2,"2nd year"),
    (3,"3rd year"),
    (4,"4th year"),
    )
    name = models.CharField(max_length=264)
    phone_no = models.CharField(max_length=13,unique=True)
    email = models.EmailField(unique=True)
    stream = models.CharField(max_length=10,choices = stream_choices)
    year = models.IntegerField(choices=year_choices)

    def __str__(self):
        return("{}, stream - {} ,year-{} ".format(self.name,self.stream,self.year))

class info(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE) #the details of who posted it

    stream_choices = (
    ('CSE','CSE'),
    ('ECE','ECE'),
    ('Mechanical','Mechanical'),
    ('Civil','Civil'),
    ('All Streams','All'),
    )

    year_choices = (
    ("1st year","1st year"),
    ("2nd year","2nd year"),
    ("3rd year","3rd year"),
    ("4th year","4th year"),
    ("All years","All years"),
    )

    stream = models.CharField(max_length=20,choices = stream_choices)
    year = models.CharField(max_length = 10 ,choices=year_choices)
    information = models.CharField(max_length=10000)
    date = models.DateField(default=date.today())

    def __str__(self):
        return("Posted by:- {} on {}".format(self.user.first_name,self.date))

messenger_app/forms.py
from django import forms
from django.core import validators
from messenger_app import models


#create forms here
class student_register_form(forms.ModelForm):
    class Meta:
        model = models.student
        fields = "__all__"

class create_post_form(forms.ModelForm):
    username = forms.CharField(max_length=264)
    password = forms.CharField(widget=forms.PasswordInput)
    send_as_message = forms.BooleanField(label="Send as message",required=False)

    class Meta:
        model = models.info
        fields = "__all__"
        widgets = {"information":forms.Textarea(),}#"user":forms.HiddenInput
        labels = {
            'stream':'For Stream',
            'year':'For Year'
        }

messenger_app/views.py
import requests

from django.shortcuts import render
from django.http import HttpResponse
from . import forms
from . import models


from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

#the view that i want to require login just put the @login_required tag.

# Create your views here.
def index(request):
    info_list = models.info.objects.all().order_by('-date')
    return_dict = {"info_list":info_list}
    return render(request,"messenger_app/homepage.html",context=return_dict)

def about(request):
    return render(request,"messenger_app/about.html")

def reg_success(request):
    return render(request,"messenger_app/reg_success.html")

def student_register(request):
    student_register_form = forms.student_register_form()
    if(request.method == "POST"):
        student_register_form = forms.student_register_form(request.POST)
        if(student_register_form.is_valid()):
            student_register_form = forms.student_register_form(request.POST)
            student_register_form.save(commit=True)
            return render(request,"messenger_app/reg_success.html")

        else:
            return HttpResponse("Failed to Save!")

    return render(request,"messenger_app/student_register_page.html",{"student_register_form":student_register_form})


def user_login(request):
    if(request.method == "POST"):
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username,password=password)

        if(user):
            if(user.is_active):
                login(request,user)
                return(HttpResponseRedirect(reverse(create_post)))

            else:
                return HttpResponse("Your account is not active!")
        else:
            return HttpResponse("Please recheck the details you have supplied either they are wrong or you are not registered")

    else:
        return render(request,"messenger_app/login.html")

def send_sms(phone,text):
    url = "https://www.fast2sms.com/dev/bulk"

    payload = "sender_id=FSTSMS&message={}&language=english&route=p&numbers={}".format(text,phone)

    headers = {
    'authorization': "BR6gtTay8dxMOQV7EbW5HC3FkIGrPwS9jLiuKJANU4vXZfDqhsIo9PptBGHvXU1dkYCbmOKewqWA2MZL",
    'Content-Type': "application/x-www-form-urlencoded",
    'Cache-Control': "no-cache",
    }

    response = requests.request("POST", url, data=payload, headers=headers)

    # if __name__ == '__main__':
    #     print(response.text)


def create_post(request):
    form = forms.create_post_form()

    if(request.method == "POST"):
        form = forms.create_post_form(request.POST)
        if(form.is_valid()):
            #authenticate the user
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username,password=password)
            if(user):
                #filled the one to one field
                form.user = user

                #commit it to databse
                form.save(commit="True")
                if(form.cleaned_data["send_as_message"]):
                    students = models.student.objects.all()
                    for s in students:
                        send_sms(s.phone_no,form.cleaned_data["information"])
                    #it will be displayed on the homepage and the user will be returned to the homepages
                return HttpResponseRedirect(reverse("index"))

            else:
                return HttpResponse("Maybe you entered username or password wrong,if the problem still persists after retrying contact the admin")
        else:
            return HttpResponse("The form you entered is Invalid!")

    return render(request,"messenger_app/create_post.html",{"create_post_form":form})

templates/messenger_app/about.html
<!DOCTYPE html>
{% extends "messenger_app/base.html "%}
{% block body_block%}
<br><br>
    <div class="jumbotron">
        <p style="font-size:20px;">Hi everyone my name is ARSHPREET SINGH i made this as my summer training project with BHASKAR SIR as my mentor,thanks a lot sir for helping me with this !</p>

<p><u><b>MY MOTIVATION TO DEVELOP THIS:- </b></u></p>

<p> We all know everyone&rsquo;s going through a tough time right now due to this pandemic but everyone&rsquo;s still doing there fair share of help to make the situation better So i also decided to help and developing this project was a very adventrous undertaking i love problem solving and tinkering with code so its been fun and i learned a lot through it.</p>

<p><u>
<b>PROBLEMS I AM TRYING TO SOLVE:-</b>
</u></p>

<p> Omg we all have experienced it very well when there&rsquo;s a quiz notification posted on our whatsapp group and we missed because either our internet was closed or there&rsquo;s been a thousand messages in our group and we are too lazy to read through them to find the important one. So, i decided why not create a web app where teachers cam post all the important notifications and when they post it will remain on the home page buy they will also be sent as a message to all the students.</p>

<p><u>
<b>TECHNOLOGIES I HAVE USED:-</b>
</u></p>

<p><u>FRONT END:-</u></p>

<p> HTML</p>

<p> CSS</p>

<p> JAVASCRIPT</p>

<p> BOOTSTRAP</p>

<p><u>BACKEND:-</u></p>

<p> PYTHON</p>

<p> DJANGO FRAMEWORK</p>

<p> SQLITE as my database engine</p>

<p><u>
<b>FUTURE VIEW:-</b>
</u></p>

<p> By no means i think this project has a limited use case and ill be actively adding features to it in future if you have any suggestions mail me at arsharsh2391@gmail.com</p>

    </div>
{%endblock%}

templates/messenger_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>base</title>
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="{%static "homepage_master.css"%}">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@600&display=swap" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    </head>
    <body>


        <h1 class = "headings"><div id="logo">

        </div> <img id = "logo" src="{%static "ccetLogoBlack.png"%}" alt="" style="width: 100px; padding:0">
Welcome to official bulletin!!!</h1>
        <div class="w3-sidebar w3-bar-block " id ="side_flick" style="width:10%">
        <h3> <b><u>Deparments</u></b> </h2>
          <a href="#" class="w3-bar-item w3-button">CSE</a>
          <a href="#" class="w3-bar-item w3-button">ECE</a>
          <a href="#" class="w3-bar-item w3-button">Mechanical</a>
          <a href="#" class="w3-bar-item w3-button">Civil</a>
        <br><br>

        <div id="heading_links">
            <a class="btn btn-primary btn-lg" href="{%url "index"%}">Home</a>
            <a class="btn btn-primary btn-lg" href="{%url "messenger_app:create_post"%}">POST</a>
            <a class="btn btn-primary btn-lg" href="{% url "messenger_app:student_register"%}">Signup!</a>
        </div>
        <p id = "signup_p">By Signing up you will recieve the notifications through a text message on the given number.</p>
        </div>
        <br><br><br><br><br><br>


        <div class="w3-sidebar w3-bar-block " id ="side_flick_right" style="width:10%">
        <h3 style="margin-left:5%"> <b>Quick links</b>  </h2>
          <a href="http://ccet.ac.in/" class="w3-bar-item w3-button">CCET</a>
          <a href="https://puchd.ac.in/" class="w3-bar-item w3-button">PU</a>
          <a href="http://eakadamik.in/ccet/" class="w3-bar-item w3-button">E-Akadamic</a>
          <a href="{%url "admin:index"%}" class="w3-bar-item w3-button">Admin</a>

        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <div id="heading_links">
            <a href="{%url "messenger_app:about"%}">About</a>
        </div>
        </div>


        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>

    </body>
</html>

templates/messenger_app/create_post.html
<!DOCTYPE html>
{% extends "messenger_app/base.html"%}
{% block body_block%}
    <div class="jumbotron">
        <form action="{% url "messenger_app:create_post"%}" method="POST">
            {{ create_post_form.as_p}}
            {% csrf_token %}
            <input class="btn btn-primary btn-lg" type="submit" name="" value="Make Post!">
        </form>
    </div>
{% endblock %}

templates/messenger_app/homepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>CCET BULLETIN</title>
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="{%static "homepage_master.css"%}">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@600&display=swap" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    </head>
    <body>


        <h1 class = "headings"><div id="logo">

        </div> <img id = "logo" src="{%static "ccetLogoBlack.png"%}" alt="" style="width: 100px; padding:0">
Welcome to official bulletin!!!</h1>
        <div class="w3-sidebar w3-bar-block " id ="side_flick" style="width:10%">
        <h3> <b><u>Deparments</u></b> </h2>
          <a href="#" class="w3-bar-item w3-button">CSE</a>
          <a href="#" class="w3-bar-item w3-button">ECE</a>
          <a href="#" class="w3-bar-item w3-button">Mechanical</a>
          <a href="#" class="w3-bar-item w3-button">Civil</a>
        <br><br><br><br>

        <div id="heading_links">
            <a class="btn btn-primary btn-lg" href="{%url "messenger_app:create_post"%}">POST</a>
            <a class="btn btn-primary btn-lg" href="{% url "messenger_app:student_register"%}">Signup!</a>
        </div>
        <p id = "signup_p">By Signing up you will recieve the notifications through a text message on the given number.</p>
        </div>
        <br><br><br><br><br><br>


        <div class="w3-sidebar w3-bar-block " id ="side_flick_right" style="width:10%">
        <h3 style="margin-left:5%"> <b>Quick links</b>  </h2>
          <a href="http://ccet.ac.in/" class="w3-bar-item w3-button">CCET</a>
          <a href="https://puchd.ac.in/" class="w3-bar-item w3-button">PU</a>
          <a href="http://eakadamik.in/ccet/" class="w3-bar-item w3-button">E-Akadamic</a>
          <a href="{%url "admin:index"%}" class="w3-bar-item w3-button">Admin</a>

        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <div id="heading_links">
            <a href="{%url "messenger_app:about"%}">About</a>
        </div>
        </div>

        <div class="container">
            <br>
            <!-- this is where the loop will run! -->
            {% if info_list %}
            {% for i in info_list %}
            <p style="color:#ffaa00;font-size:20px;"> &#8728; {{i.user.first_name}} {{i.user.last_name}} posted this on {{i.date}} for {{i.year}} of {{i.stream}} :- </p>
            <div class="jumbotron" id="posted_notifications">
                <!-- all the posted notifications will be dynamically posted here -->
                <pre><p style="font-size:18px;">{{i.information}}</p></pre>
            </div>
            {%endfor%}
            {% else %}
            <h2>No infos posted yet!</h2>
            {% endif %}
            <p style="color:#ffaa00;font-size:20px;"> &#8728; Arshpreet Singh has posted this on July 30,2020 for All years for All Streams </p>
            <div class="jumbotron" id="posted_notifications">
                <!-- all the posted notifications will be dynamically posted here -->
                <p style="font-size:20px;">Hi everyone my name is ARSHPREET SINGH i made this as my summer training project with BHASKAR SIR as my mentor,thanks a lot sir for helping me with this !</p>

<p><u><b>MY MOTIVATION TO DEVELOP THIS:- </b></u></p>

<p> We all know everyone&rsquo;s going through a tough time right now due to this pandemic but everyone&rsquo;s still doing there fair share of help to make the situation better So i also decided to help and developing this project was a very adventrous undertaking i love problem solving and tinkering with code so its been fun and i learned a lot through it.</p>

<p><u>
    <b>PROBLEMS I AM TRYING TO SOLVE:-</b>
</u></p>

<p> Omg we all have experienced it very well when there&rsquo;s a quiz notification posted on our whatsapp group and we missed because either our internet was closed or there&rsquo;s been a thousand messages in our group and we are too lazy to read through them to find the important one. So, i decided why not create a web app where teachers cam post all the important notifications and when they post it will remain on the home page buy they will also be sent as a message to all the students.</p>

<p><u>
    <b>TECHNOLOGIES I HAVE USED:-</b>
</u></p>

<p><u>FRONT END:-</u></p>

<p> HTML</p>

<p> CSS</p>

<p> JAVASCRIPT</p>

<p> BOOTSTRAP</p>

<p><u>BACKEND:-</u></p>

<p> PYTHON</p>

<p> DJANGO FRAMEWORK</p>

<p> SQLITE as my database engine</p>

<p><u>
<b>FUTURE VIEW:-</b>
</u></p>

<p> By no means i think this project has a limited use case and ill be actively adding features to it in future if you have any suggestions mail me at arsharsh2391@gmail.com</p>
</div>
            <div class="">
                <p style="color:#ffaa00;font-size:20px;"> &#8728; Arshpreet Singh has posted this on July 30,2020 for All years for All Streams </p>
                <div class="jumbotron" id="posted_notifications">
                    <p><b>HOW TO USE</b></p>

<p><b>As a teacher:-</b></p>

<p>Every teacher is provided with a unique username. To make a post click on the POST button at the left side in the user dropdown menu select your user name ,select other options and finally its as easy as making a click</p>

<p><b>As a student:-</b></p>

<p>Just Sign up and you&rsquo;ll be good to go you&rsquo;ll receive text messages of the posted notifications on the given mobile number.</p>
                </div>



    </body>
</html>

templates/messenger_app/login.html
<!DOCTYPE html>
{% extends "messenger_app/base.html"%}
{% block body_block%}
<br><br><br><br><br>
<div class="jumbotron">
    <h2>Fill in the details!</h2>
    <form class="" action="{%url "messenger_app:user_login"%}" method="post">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" placeholder="Username">
        <br><br><br>
        <label for="password">Password: </label>
        <input type="password" name="password" value="">
        <br><br>
        <input class="btn btn-primary btn-lg" type="submit" name="" value="Login">
    </form>
</div>
{% endblock %}

templates/messenger_app/reg_success.html
<!DOCTYPE html>
{%extends "messenger_app/base.html"%}
{%block body_block%}
    <br><br>
    <div class="container">
        <div class="jumbotron">
            <h1>REGISTERED SUCCESFULLY!</h1>
            <br> <br>
            <h2>Can now return to home page and notifications from now on will be delivered to you as a text message on the provided mobile number.</h2>
        </div>
    </div>

{% endblock %}

templates/messenger_app/student_register_page.html
<!DOCTYPE html>
{% extends "messenger_app/base.html"%}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Register</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>
        {% block body_block%}
        <div class="container">

            <div class="jumbotron">
                <!-- <h2>By Registering you agree to recieving information as a text message and as an email to the given mobile number and email</h2> -->
                <h2>Signup Now And You Will Receive Information As a Text Message As Soon as a Teacher Posts it here!!!</h2>
            </div>
            <br>
        </div>
        <div class="container">
            <div class="jumbotron">
                <form method="post">
                    {{student_register_form.as_p}}
                    {% csrf_token %}
                    <!-- <a class="btn btn-success btn-lg" href="https://www.google.com/">Google</a> -->
                    <input class="btn btn-success btn-lg" type="Submit" name="" value="Register Now!">
                </form>
            </div>
        </div>
        {% endblock %}
    </body>
</html>